// <auto-generated />
using System;
using ERISMobileWebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ERIS.MobileWebAPI.Migrations
{
    [DbContext(typeof(ERISDbContext))]
    [Migration("20220503042447_Login")]
    partial class Login
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ERISMobileWebAPI.Models.AssessmentDetails", b =>
                {
                    b.Property<int>("AssessmentDetailsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssessmentID")
                        .HasColumnType("int");

                    b.Property<decimal>("BushesShrubsCoverageOnSlope")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ClayEstimate")
                        .HasColumnType("decimal(5,3)");

                    b.Property<int>("ClosedLanes")
                        .HasColumnType("int");

                    b.Property<int>("CrackBulge")
                        .HasColumnType("int");

                    b.Property<decimal>("CrackDepth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CrackHorizontalDisplacement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CrackLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CrackSettlement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CrackVerticalDisplacement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GravelEstimate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GroundCoverCoverageOnSlope")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HasBedding")
                        .HasColumnType("bit");

                    b.Property<bool>("HasCloggedInlet")
                        .HasColumnType("bit");

                    b.Property<bool>("HasCompromisedDrains")
                        .HasColumnType("bit");

                    b.Property<bool>("HasFractures")
                        .HasColumnType("bit");

                    b.Property<bool>("HasImpactedAdjacentProperties")
                        .HasColumnType("bit");

                    b.Property<bool>("HasImpactedAdjacentStructures")
                        .HasColumnType("bit");

                    b.Property<bool>("HasImpactedAdjacentUtilities")
                        .HasColumnType("bit");

                    b.Property<bool>("HasJoints")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMaybeImpactedAdjacentProperties")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMaybeImpactedAdjacentStructures")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMaybeImpactedAdjacentUtilities")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSurfaceRunoff")
                        .HasColumnType("bit");

                    b.Property<bool>("HasTorrentSurgeFlood")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdvancing")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompound")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConfined")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDry")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnlarging")
                        .HasColumnType("bit");

                    b.Property<bool>("IsErosion")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFall")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFlow")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFlowingWater")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFollowUpActionButtressToeOfLandslide")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFollowUpActionConstructTemporaryShoring")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFollowUpActionDesignAndPlans")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFollowUpActionDewaterWithHorizontalDrains")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFollowUpActionGeologicalMapping")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFollowUpActionInstallErosionControl")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFollowUpActionOpenHighwayShoulder")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFollowUpActionOpenHighwayTraffic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFollowUpActionPlaceRockSlopeProtection")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFollowUpActionReconstructSlopeToOriginalCondition")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFollowUpActionReconstructSlopeWithGeosynthetics")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFollowUpActionRepairCulvertDrainagePipe")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFollowUpActionRoutineVisualMonitor")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFollowUpActionSubsurfaceExploration")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFollowUpActionSurveySite")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHighwayOpen")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImmediateActionButtressToeOfLandslide")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImmediateActionCloseHighWayBothDirections")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImmediateActionCloseHighwayOneDirection")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImmediateActionConstructTemporaryShoring")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImmediateActionCoverSlopeWithPlastic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImmediateActionDewaterWithHorizontalDrains")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImmediateActionDewaterWithPumpTrench")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImmediateActionDivertSurfaceWaterRunoff")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImmediateActionOpenHighwayShoulder")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImmediateActionOpenHighwayTraffic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImmediateActionPlaceKRailOrFence")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImmediateActionPlaceRockSlopeProtection")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImmediateActionReconstructSlopeToOriginalCondition")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImmediateActionReconstructSlopeWithGeosynthetics")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImmediateActionRemoveCulvertBlockage")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImmediateActionRemoveLandslideDebris")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImmediateActionRoutineVisualMonitor")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIndentedByRocks")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLaneClosed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMoist")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMoving")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOneWayClosed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPavementGroundCracks")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRetrogressing")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsScouredToe")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSeep")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShoulderClosed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSlide")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSoil")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpread")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpring")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSurfacialSloughing")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTopple")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTwoWayClosed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWashout")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWet")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWidening")
                        .HasColumnType("bit");

                    b.Property<decimal>("LandslideLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LandslideSlope")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("LandslideWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MainScarpHeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ObservationsAndNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OpenedLanesCount")
                        .HasColumnType("int");

                    b.Property<decimal>("OriginalSlope")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RoadwayEncroachedLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RoadwayEncroachedWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SandEstimate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SiltEstimate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SlopeHeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TreesCoverageOnSlope")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AssessmentDetailsID");

                    b.ToTable("AssessmentDetails");
                });

            modelBuilder.Entity("ERISMobileWebAPI.Models.AssessmentProfile", b =>
                {
                    b.Property<int>("AssessmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssessmentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateIncidentReported")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistrictContactCellPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistrictContactFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistrictContactLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistrictContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistrictContactSNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsUploaded")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostMile")
                        .HasColumnType("int");

                    b.Property<string>("ProjectID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Route")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssessmentID");

                    b.ToTable("AssessmentProfile");
                });

            modelBuilder.Entity("ERISMobileWebAPI.Models.Login", b =>
                {
                    b.Property<int>("LoginID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginID");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("ERISMobileWebAPI.Models.Photo", b =>
                {
                    b.Property<int>("PhotoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssessmentID")
                        .HasColumnType("int");

                    b.Property<string>("AssociatedMeasurement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhotoID");

                    b.ToTable("Photo");
                });
#pragma warning restore 612, 618
        }
    }
}
