CREATE TABLE [dbo].[AssessmentDetails] (
    [AssessmentDetailsID]                                  INT             IDENTITY (1, 1) NOT NULL,
    [AssessmentID]                                         INT             NOT NULL,
    [IsFall]                                               BIT             NOT NULL,
    [IsTopple]                                             BIT             NOT NULL,
    [IsSlide]                                              BIT             NOT NULL,
    [IsSpread]                                             BIT             NOT NULL,
    [IsFlow]                                               BIT             NOT NULL,
    [IsCompound]                                           BIT             NOT NULL,
    [IsErosion]                                            BIT             NOT NULL,
    [IsSurfacialSloughing]                                 BIT             NOT NULL,
    [IsScouredToe]                                         BIT             NOT NULL,
    [IsWashout]                                            BIT             NOT NULL,
    [IsAdvancing]                                          BIT             NOT NULL,
    [IsRetrogressing]                                      BIT             NOT NULL,
    [IsEnlarging]                                          BIT             NOT NULL,
    [IsWidening]                                           BIT             NOT NULL,
    [IsMoving]                                             BIT             NOT NULL,
    [IsConfined]                                           BIT             NOT NULL,
    [IsPavementGroundCracks]                               BIT             NOT NULL,
    [CrackLength]                                          DECIMAL (18, 2) NOT NULL,
    [CrackHorizontalDisplacement]                          DECIMAL (18, 2) NOT NULL,
    [CrackVerticalDisplacement]                            DECIMAL (18, 2) NOT NULL,
    [CrackDepth]                                           DECIMAL (18, 2) NOT NULL,
    [CrackSettlement]                                      DECIMAL (18, 2) NOT NULL,
    [CrackBulge]                                           INT             NOT NULL,
    [IsIndentedByRocks]                                    BIT             NOT NULL,
    [IsRock]                                               BIT             NOT NULL,
    [HasBedding]                                           BIT             NOT NULL,
    [HasJoints]                                            BIT             NOT NULL,
    [HasFractures]                                         BIT             NOT NULL,
    [IsSoil]                                               BIT             NOT NULL,
    [ClayEstimate]                                         DECIMAL (5, 3)  NOT NULL,
    [BushesShrubsCoverageOnSlope]                          DECIMAL (18, 2) NOT NULL,
    [SiltEstimate]                                         DECIMAL (18, 2) NOT NULL,
    [SandEstimate]                                         DECIMAL (18, 2) NOT NULL,
    [GravelEstimate]                                       DECIMAL (18, 2) NOT NULL,
    [TreesCoverageOnSlope]                                 DECIMAL (18, 2) NOT NULL,
    [GroundCoverCoverageOnSlope]                           DECIMAL (18, 2) NOT NULL,
    [SlopeHeight]                                          DECIMAL (18, 2) NOT NULL,
    [OriginalSlope]                                        DECIMAL (18, 2) NOT NULL,
    [LandslideWidth]                                       DECIMAL (18, 2) NOT NULL,
    [LandslideLength]                                      DECIMAL (18, 2) NOT NULL,
    [MainScarpHeight]                                      DECIMAL (18, 2) NOT NULL,
    [LandslideSlope]                                       DECIMAL (7, 2)  NOT NULL,
    [RoadwayEncroachedLength]                              DECIMAL (18, 2) NOT NULL,
    [RoadwayEncroachedWidth]                               DECIMAL (18, 2) NOT NULL,
    [IsDry]                                                BIT             NOT NULL,
    [IsMoist]                                              BIT             NOT NULL,
    [IsWet]                                                BIT             NOT NULL,
    [IsFlowingWater]                                       BIT             NOT NULL,
    [IsSeep]                                               BIT             NOT NULL,
    [IsSpring]                                             BIT             NOT NULL,
    [IsHighwayOpen]                                        BIT             NOT NULL,
    [IsShoulderClosed]                                     BIT             NOT NULL,
    [IsLaneClosed]                                         BIT             NOT NULL,
    [ClosedLanes]                                          INT             NOT NULL,
    [IsOneWayClosed]                                       BIT             NOT NULL,
    [IsTwoWayClosed]                                       BIT             NOT NULL,
    [HasCloggedInlet]                                      BIT             NOT NULL,
    [HasCompromisedDrains]                                 BIT             NOT NULL,
    [HasSurfaceRunoff]                                     BIT             NOT NULL,
    [HasTorrentSurgeFlood]                                 BIT             NOT NULL,
    [HasImpactedAdjacentUtilities]                         BIT             NOT NULL,
    [HasImpactedAdjacentProperties]                        BIT             NOT NULL,
    [HasImpactedAdjacentStructures]                        BIT             NOT NULL,
    [HasMaybeImpactedAdjacentUtilities]                    BIT             NOT NULL,
    [HasMaybeImpactedAdjacentProperties]                   BIT             NOT NULL,
    [HasMaybeImpactedAdjacentStructures]                   BIT             NOT NULL,
    [IsImmediateActionOpenHighwayTraffic]                  BIT             NOT NULL,
    [IsImmediateActionOpenHighwayShoulder]                 BIT             NOT NULL,
    [IsImmediateActionCloseHighwayOneDirection]            BIT             NOT NULL,
    [IsImmediateActionCloseHighWayBothDirections]          BIT             NOT NULL,
    [IsImmediateActionRemoveLandslideDebris]               BIT             NOT NULL,
    [IsImmediateActionPlaceKRailOrFence]                   BIT             NOT NULL,
    [IsImmediateActionCoverSlopeWithPlastic]               BIT             NOT NULL,
    [IsImmediateActionDivertSurfaceWaterRunoff]            BIT             NOT NULL,
    [IsImmediateActionRemoveCulvertBlockage]               BIT             NOT NULL,
    [IsImmediateActionDewaterWithPumpTrench]               BIT             NOT NULL,
    [IsImmediateActionDewaterWithHorizontalDrains]         BIT             NOT NULL,
    [IsImmediateActionConstructTemporaryShoring]           BIT             NOT NULL,
    [IsImmediateActionButtressToeOfLandslide]              BIT             NOT NULL,
    [IsImmediateActionPlaceRockSlopeProtection]            BIT             NOT NULL,
    [IsImmediateActionRoutineVisualMonitor]                BIT             NOT NULL,
    [IsImmediateActionReconstructSlopeToOriginalCondition] BIT             NOT NULL,
    [IsImmediateActionReconstructSlopeWithGeosynthetics]   BIT             NOT NULL,
    [IsFollowUpActionOpenHighwayTraffic]                   BIT             NOT NULL,
    [IsFollowUpActionOpenHighwayShoulder]                  BIT             NOT NULL,
    [IsFollowUpActionDewaterWithHorizontalDrains]          BIT             NOT NULL,
    [IsFollowUpActionConstructTemporaryShoring]            BIT             NOT NULL,
    [IsFollowUpActionButtressToeOfLandslide]               BIT             NOT NULL,
    [IsFollowUpActionPlaceRockSlopeProtection]             BIT             NOT NULL,
    [IsFollowUpActionRoutineVisualMonitor]                 BIT             NOT NULL,
    [IsFollowUpActionReconstructSlopeToOriginalCondition]  BIT             NOT NULL,
    [IsFollowUpActionReconstructSlopeWithGeosynthetics]    BIT             NOT NULL,
    [IsFollowUpActionRepairCulvertDrainagePipe]            BIT             NOT NULL,
    [IsFollowUpActionInstallErosionControl]                BIT             NOT NULL,
    [IsFollowUpActionSurveySite]                           BIT             NOT NULL,
    [IsFollowUpActionGeologicalMapping]                    BIT             NOT NULL,
    [IsFollowUpActionSubsurfaceExploration]                BIT             NOT NULL,
    [IsFollowUpActionDesignAndPlans]                       BIT             NOT NULL,
    [OpenedLanesCount]                                     INT             NOT NULL,
    [ObservationsAndNotes]                                 NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_AssessmentDetails] PRIMARY KEY CLUSTERED ([AssessmentDetailsID] ASC)
);

